[package]
name = "bevy_swift"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
bevy_ecs = "0.17.2"
winit = "0.30.12"
wgpu = "26.0.1"
pollster = "0.4.0"
glam = "0.27"
bytemuck = { version = "1", features = ["derive"] }